name: betro_dart_lib
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cryptography: ^2.0.1
  encrypt: ^5.0.0
  pointycastle: ^3.0.1

dev_dependencies:
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
