name: betro_dart_lib
description: A new flutter plugin project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  lints: ^2.0.0
  cryptography: ^2.0.5
  collection: ^1.16.0
  encrypt: ^5.0.1
  json_annotation: ^4.6.0
  webcrypto:
    git: https://github.com/google/webcrypto.dart
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: "^1.5.0"
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `some_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------
